name: 9-test
on:
  workflow_dispatch

env:
  VERSION: "v.1.0.0"
  DEBUG_LS: true
  NODE_VERS:    '18.18.2'
  #NODE_VERS:   '18.17.1'
  YARN_VERS:    '1.22.10'
  NPM_VERS:     '10.2.5'
  NODEGYP_VERS: '10.0.1'

jobs:
  test:
    runs-on: ubuntu-latest
    # timeout-minutes: 30

    steps:
    - run: |
        echo NODE_VERSION:    ${{ env.NODE_VERS    }}
        echo YARN_VERSION:    ${{ env.YARN_VERS    }}
        echo NPM_VERSION:     ${{ env.NPM_VERS     }}
        echo NODEGYP_VERSION: ${{ env.NODEGYP_VERS }}

    - run: npm install -g "yarn@${{ env.YARN_VERS }}"
    - run: npm install -g "npm@${{ env.NPM_VERS }}"
    - run: npm install -g "node-gyp@10.0.1"
    - run: npm install -g 'node-gyp@{{ env.NODEGYP_VERS }}'

    - run: npm install -g "yarn@${{ env.YARN_VERS }}" "npm@${{ env.NPM_VERS }}" 'node-gyp@{{ env.NODEGYP_VERS }}'
    
    - run: npm install -g yarn@${{ env.YARN_VERS }} npm@${{ env.NPM_VERS }} node-gyp@{{ env.NODEGYP_VERS }}
