# Copyright 2020 Signal Messenger, LLC
# SPDX-License-Identifier: AGPL-3.0-only

name: Danger
on:
  workflow_dispatch:
#  pull_request:

jobs:
  danger:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history
      - uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'
      - run: npm install -g npm@10.2.5
      - name: Cache danger node_modules
        id: cache-desktop-modules
        uses: actions/cache@v3
        with:
          path: danger/node_modules
          key: danger-${{ runner.os }}-${{ hashFiles('danger/package.json', 'danger/package-lock.json') }}
      - name: Install danger node_modules
        if: steps.cache-desktop-modules.outputs.cache-hit != 'true'
        run: cd danger && npm ci
      - name: Run DangerJS
        run: npm run danger:ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.AUTOMATED_GITHUB_PAT }}
